name: CI/CD for PlatformIO

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'platformio.ini'
      - '.github/workflows/**'

      - '!.github/workflows/release.yml'
      - '!**/README.md'

jobs:
  platformio-build-esp32dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Build PlatformIO Project for ESP32
      run: platformio run -e esp32dev

    - name: Move binaries to artifacts folder
      run: |
        mkdir -p artifacts/esp32dev
        mv .pio/build/esp32dev/*.bin artifacts/esp32dev

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: platformio-build
        path: artifacts

    - name: Cleanup
      run: rm -rf .pio